baseurl = "https://walterkuppens.com/"
languageCode = "en-us"
title = "Walter Kuppens"

[params]
  description = "Software development and technology blog written by Walter Kuppens."
  author = "Walter Kuppens"
  primaryColor = "#375EAB"
  secondaryColor = "#1847A3"
  analytics = "UA-72614951-1"

  [params.links]
    [params.links.Blog]
      url = "/"
      title = "Blog"
      weight = 20
    [params.links.Projects]
      url = "/projects"
      title = "Projects"
      weight = 10
    [params.links.Archive]
      url = "/archive"
      title = "Archive"
      weight = 5
    [params.links.About]
      url = "/about"
      title = "About"
      weight = 0
