baseurl = "https://walterkuppens.com"
languageCode = "en-us"
title = "Walter Kuppens"

pygmentsUseClasses = true
pygmentsStyle = "trac"

[params]
  description = "Software development and technology blog written by Walter Kuppens."
  author = "Walter Kuppens"
  copyright = "© 2016 Walter Kuppens. CC BY-SA 3.0"

  primaryColor = "#EFEFEF"
  secondaryColor = "#EFEFEF"

  analytics = "UA-72614951-1"
  favicon = "/favicon.ico?v=1"

  # Social urls.
  github = "https://github.com/Reshurum"
  twitter = "https://twitter.com/Reshurum"
  googleplus = "https://plus.google.com/+WalterKuppens"

  [params.links]
    [params.links.Blog]
      url = "/"
      title = "Blog"
      weight = 20
    [params.links.Projects]
      url = "/projects/"
      title = "Projects"
      weight = 10
    [params.links.Archive]
      url = "/archive/"
      title = "Archive"
      weight = 5
    [params.links.About]
      url = "/about/"
      title = "About"
      weight = 0
