baseurl = "https://walterkuppens.com/"
languageCode = "en-us"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License."
title = "Walter Kuppens"

pygmentsUseClasses = true
pygmentsStyle = "trac"

[params]
  description = "Software development and technology blog written by Walter Kuppens."
  tagline = "A place for me to spout about technology"
  author = "Walter Kuppens"
  copyright = "© 2016 Walter Kuppens. CC BY-SA 3.0"

  primaryColor = "#f5f5f5"
  secondaryColor = "#efefef"

  analytics = "UA-72614951-1"
  favicon = "/favicon.ico?v=2"

  # Social urls.
  github = "https://github.com/Reshurum"
  twitter = "https://twitter.com/Reshurum"
  googleplus = "https://plus.google.com/+WalterKuppens"

  # Similar to baseurl but with http and no trailing slash for RSS 2.0 spec.
  rssbaseurl = "http://walterkuppens.com"

  [params.links]
    [params.links.Blog]
      url = ""
      title = "Blog"
      weight = 20
    [params.links.Projects]
      url = "projects"
      title = "Projects"
      weight = 10
    [params.links.Archive]
      url = "archive"
      title = "Archive"
      weight = 5
    [params.links.About]
      url = "about"
      title = "About"
      weight = 0
